local Math = require("core.math")

local Vector2    = Math.Vector2
local Vector3    = Math.Vector3
local Quaternion = Math.Quaternion
local Matrix3    = Math.Matrix3
local Matrix4    = Math.Matrix4
local Transform  = Math.Transform
local Color3     = Math.Color3
local Color4     = Math.Color4

-- Vector2
local v2 = Vector2.new(1, 2)
local v2b = Vector2.new(3, 4)
print(v2)
print(v2:length())
print(v2 + v2b)
print(v2 - v2b)
print(v2 * 2)
print(v2 / 2)
print(-v2)
print(v2 == v2b)
print(v2:dot(v2b))
print(v2:cross(v2b))
print(v2:distance(v2b))
print(v2:angle(v2b))
print(v2:normalized())
print(v2:perpendicular())
print(v2:absolute())
print(v2:reflect(Vector2.UP))
print(v2:project(v2b))
print(v2:interpolate(v2b, 0.5))
print(v2:clamped(0, 0, 2, 2))
print(v2:approximately(v2b, 0.1))
print(v2:dominant())
print(v2:recessive())
print(Vector2.minimum(v2, v2b))
print(Vector2.maximum(v2, v2b))
print(Vector2.ZERO)
print(Vector2.ONE)
print(Vector2.UP)
print(Vector2.DOWN)
print(Vector2.LEFT)
print(Vector2.RIGHT)

-- Vector3
local v3 = Vector3.new(1, 2, 3)
local v3b = Vector3.new(4, 5, 6)
print(v3)
print(v3:length())
print(v3 + v3b)
print(v3 - v3b)
print(v3 * 2)
print(v3 / 2)
print(-v3)
print(v3 == v3b)
print(v3:dot(v3b))
print(v3:cross(v3b))
print(v3:distance(v3b))
print(v3:angle(v3b))
print(v3:angle(v3b, 0, 1, 0))
print(v3:normalized())
print(v3:absolute())
print(v3:reflect(Vector3.UP))
print(v3:project(v3b))
print(v3:interpolate(v3b, 0.5))
print(v3:clamped(0, 0, 0, 2, 2, 2))
print(v3:approximately(v3b, 0.1))
print(v3:dominant())
print(v3:recessive())
print(Vector3.minimum(v3, v3b))
print(Vector3.maximum(v3, v3b))
print(Vector3.ZERO)
print(Vector3.ONE)
print(Vector3.UP)
print(Vector3.DOWN)
print(Vector3.LEFT)
print(Vector3.RIGHT)
print(Vector3.FORWARD)
print(Vector3.BACK)

-- Quaternion
local q  = Quaternion.euler(0, 90, 0)
local q2 = Quaternion.around(90, 0, 1, 0)
local q3 = Quaternion.between(0, 0, 1, 1, 0, 0)
local q4 = Quaternion.look(0, 0, 1, 0, 1, 0)
print(q)
print(q2)
print(q3)
print(q4)
print(q + q2)
print(q - q2)
print(q * q2)
print(q * 2)
print(q == q2)
print(q:length())
print(q:dot(q2))
print(q:normalized())
print(q:conjugate())
print(q:inverse())
print(q:interpolate(q2, 0.5))
print(q:approximately(q2, 0.1))
local rx, ry, rz = q:euler()
print(rx, ry, rz)
print(Quaternion.IDENTITY)

-- Matrix3
local m3  = Matrix3.compose(1, 2, 0, 1, 1)
local m3b = Matrix3.identity()
print(m3)
print(m3b)
print(m3 + m3b)
print(m3 - m3b)
print(m3 * m3b)
print(m3 * 2)
print(m3 == m3b)
print(m3:get(1, 1))
m3:set(1, 1, 99)
m3:set(1, 1, 1)
print(m3:transposed())
print(m3:inverted())
print(m3:determinant())
print(m3:approximately(m3b, 0.1))
local tx, ty = m3:translation()
print(tx, ty)
print(m3:rotation())
local sx, sy = m3:scale()
print(sx, sy)
local dtx, dty, drot, dsx, dsy = m3:decompose()
print(dtx, dty, drot, dsx, dsy)
print(Matrix3.IDENTITY)
print(Matrix3.translate(1, 2))
print(Matrix3.rotate(45))
print(Matrix3.scale(2, 3))
print(Matrix3.orthographic(-1, 1, -1, 1))

-- Matrix4
local m4  = Matrix4.compose(1,2,3, 0,0,0,1, 1,1,1)
local m4b = Matrix4.identity()
print(m4)
print(m4b)
print(m4 + m4b)
print(m4 - m4b)
print(m4 * m4b)
print(m4 * 2)
print(m4 == m4b)
print(m4:get(1, 1))
m4:set(1, 1, 99)
m4:set(1, 1, 1)
print(m4:transposed())
print(m4:inverted())
print(m4:determinant())
print(m4:approximately(m4b, 0.1))
local tx, ty, tz = m4:translation()
print(tx, ty, tz)
local qx, qy, qz, qw = m4:rotation()
print(qx, qy, qz, qw)
local sx, sy, sz = m4:scale()
print(sx, sy, sz)
local dtx, dty, dtz, dqx, dqy, dqz, dqw, dsx, dsy, dsz = m4:decompose()
print(dtx, dty, dtz, dqx, dqy, dqz, dqw, dsx, dsy, dsz)
local ax, ay, az = m4:anterior()
print(ax, ay, az)
local px, py, pz = m4:posterior()
print(px, py, pz)
local supx, supy, supz = m4:superior()
print(supx, supy, supz)
local ix, iy, iz = m4:inferior()
print(ix, iy, iz)
local dx, dy, dz = m4:dexter()
print(dx, dy, dz)
local sinx, siny, sinz = m4:sinister()
print(sinx, siny, sinz)
print(Matrix4.IDENTITY)
print(Matrix4.translate(1, 2, 3))
print(Matrix4.rotate(0, 0, 0, 1))
print(Matrix4.scale(1, 2, 3))
print(Matrix4.perspective(1.5708, 1.777, 0.1, 1000))
print(Matrix4.orthographic(-1, 1, -1, 1, 0.1, 100))
print(Matrix4.look(0, 0, 5, 0, 0, 0, 0, 1, 0))

-- Transform
local t  = Transform.new(1,2,3, 0,0,0,1, 1,1,1)
local t2 = Transform.new()
print(t)
print(t2)
print(t * t2)
print(t == t2)
print(t.tx, t.ty, t.tz)
print(t.qx, t.qy, t.qz, t.qw)
print(t.sx, t.sy, t.sz)
local fx, fy, fz = t:forward()
print(fx, fy, fz)
local rx, ry, rz = t:right()
print(rx, ry, rz)
local ux, uy, uz = t:up()
print(ux, uy, uz)
local px, py, pz = t:point(1, 0, 0)
print(px, py, pz)
local ddx, ddy, ddz = t:direction(0, 1, 0)
print(ddx, ddy, ddz)
print(t:matrix())
print(t:inversed())
print(t:interpolate(t2, 0.5))
print(t:approximately(t2, 0.1))
print(Transform.IDENTITY)

-- Color3
local c3  = Color3.new(1, 0.5, 0)
local c3b = Color3.new(0, 0.5, 1)
print(c3)
print(c3 + c3b)
print(c3 - c3b)
print(c3 * 2)
print(c3 * c3b)
print(c3 / 2)
print(c3 == c3b)
print(c3:luminance())
print(c3:difference(c3b))
print(c3:inverted())
print(c3:clamped())
print(c3:gamma(2.2))
print(c3:interpolate(Color3.WHITE, 0.5))
print(c3:approximately(c3b, 0.1))
print(Color3.new())
print(Color3.rgb(255, 128, 0))
print(Color3.hsv(120, 1, 1))
print(Color3.hex(0xFF8800))
print(Color3.WHITE)
print(Color3.BLACK)
print(Color3.RED)
print(Color3.GREEN)
print(Color3.BLUE)
print(Color3.YELLOW)
print(Color3.CYAN)
print(Color3.MAGENTA)

-- Color4
local c4  = Color4.new(1, 0.5, 0, 0.8)
local c4b = Color4.new(0, 0.5, 1, 1)
print(c4)
print(c4 + c4b)
print(c4 - c4b)
print(c4 * 2)
print(c4 * c4b)
print(c4 / 2)
print(c4 == c4b)
print(c4:luminance())
print(c4:difference(c4b))
print(c4:inverted())
print(c4:clamped())
print(c4:gamma(2.2))
print(c4:premultiplied())
print(c4:interpolate(Color4.WHITE, 0.5))
print(c4:approximately(c4b, 0.1))
print(Color4.new())
print(Color4.rgb(255, 128, 0, 200))
print(Color4.hsv(120, 1, 1, 1))
print(Color4.hex(0xFF8800FF))
print(Color4.WHITE)
print(Color4.BLACK)
print(Color4.RED)
print(Color4.GREEN)
print(Color4.BLUE)
print(Color4.YELLOW)
print(Color4.CYAN)
print(Color4.MAGENTA)
print(Color4.TRANSPARENT)